version: '3.7'
services:
    postgres:
        image: postgres:11.9
        environment:
          - POSTGRES_USER=cc_playground
          - POSTGRES_PASSWORD=cc_playground
          - POSTGRES_DB=cc_playground
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 54321:5432
        volumes:
          - /var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"
    api:
      container_name: cc_playground_api
      depends_on:
        - postgres
      build:
        context: ../
        dockerfile: docker/api-Dockerfile
      volumes:
        - ../:/app
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://cc_playground:cc_playground@postgres/cc_playground
